os: osx
language: objective-c
osx_image: xcode8

script: 
  - set -o pipefail
  - xcodebuild build-for-testing test-without-building -workspace Action.xcworkspace -scheme Action -sdk iphonesimulator -destination "name=iPhone SE" | xcpretty -c
  - swift build

